
# gemini-3-flash-preview
# Gemini 2.5 Flash

gemini_llm:
  model: "openai/gemini-2.0-flash"
  temperature: 0.7
  base_url: "https://generativelanguage.googleapis.com/v1beta/openai/"

openai_llm:
  model: "openai/gpt-4o-mini"
  temperature: 0.7
  base_url: "https://api.openai.com/v1"


#llama-3.2-90b-text-preview
groq_llm:
  model: "groq/gpt-oss-120b" 
  temperature: 0.7
  base_url: "https://api.groq.com/openai/v1"
  max_completion_tokens : 8192
  top_p : 1
  #reasoning_effort : "medium"
  #stream : True
  #stop : None


deepseek_llm:
  model: "deepseek/deepseek-chat"
  temperature: 0.7
  base_url: "https://api.deepseek.com"


ollama_llm:
  model: "ollama/llama3:70b"
  temperature: 0.7
  base_url: "http://localhost:11434/api/tags"


